version: '3'

services:
    web:     
        image: nginx:latest
        container_name: my-nginx
        ports:
            - "8080:80"
        volumes:
          - ./app:/app
          - ./nginx-conf:/etc/nginx/conf.d/